<?php



define('COREPATH',  'core'.DIRECTORY_SEPARATOR);
define('VIEWSPATH',  'views'.DIRECTORY_SEPARATOR);
define('CONTROLLERSPATH',  'controllers'.DIRECTORY_SEPARATOR);
define('MODELSPATH',  'models'.DIRECTORY_SEPARATOR);
define('STYLESPATH', 'assets'.DIRECTORY_SEPARATOR.'styles'.DIRECTORY_SEPARATOR);
define('FILESPATH', 'assets'.DIRECTORY_SEPARATOR.'files'.DIRECTORY_SEPARATOR);
define('IMAGESPATH', 'assets'.DIRECTORY_SEPARATOR.'images'.DIRECTORY_SEPARATOR);
define('JAVASCRIPTPATH', 'assets'.DIRECTORY_SEPARATOR.'js'.DIRECTORY_SEPARATOR);